apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: my-simple-acc
  namespace: accelerator-system
spec:
  git:
    url: https://github.com/myminseok/tap-catalog
    ref:
      branch: main
