apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: default-team
  description: Default Team
spec:
  type: team
  profile:
    displayName: Default Team
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: default-org
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: myminseok@naver.com
spec:
  profile:
    displayName: User
    email: myminseok@naver.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
